#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
  if [ -f "/opt/homebrew/bin/brew" ]; then # Apple Silicon
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [ -f "/usr/local/bin/brew" ]; then # Intel
    eval "$(/usr/local/bin/brew shellenv)"
  fi
fi
